### ISSUE TITLE
Exception: Failure delivering result ResultInfo

### ISSUE THREAD

**Issue by vdrahorad-paylocity** [docusign/mobile-android-sdk#54] opened 2024-08-13 12:45 UTC
Hello, while using signature document upload, in certain cases app crashes.

**Issue Summary:**
The app crashes when using the document upload feature in the Signature component under certain conditions.

**Steps to Reproduce:**

1. In App Management, disable the system "Photos" app.
2. Open the Signature component in the DocuSign SDK.
3. Tap the "UPLOAD" tab and then tap the "UPLOAD YOUR SIGNATURE" button.
4. Refuse the Camera permission when prompted.
5. The app crashes.

Crash Log:

```
FATAL EXCEPTION: main
Process: com.paylocity.ngmobileqa.debug, PID: 4616
java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=2, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.paylocity.ngmobileqa.debug/com.docusign.androidsdk.ui.activities.CaptiveSigningActivity}: java.lang.NullPointerException: Parameter specified as non-null is null: method androidx.activity.result.contract.ActivityResultContracts$StartActivityForResult.createIntent, parameter input
    at android.app.ActivityThread.deliverResults(ActivityThread.java:5898)
    at android.app.ActivityThread.handleSendResult(ActivityThread.java:5937)
    at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
    at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:144)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:101)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2643)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:257)
    at android.os.Looper.loop(Looper.java:368)
    at android.app.ActivityThread.main(ActivityThread.java:8839)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method androidx.activity.result.contract.ActivityResultContracts$StartActivityForResult.createIntent, parameter input
    at androidx.activity.result.contract.ActivityResultContracts$StartActivityForResult.createIntent(Unknown Source:9)
    at androidx.activity.result.contract.ActivityResultContracts$StartActivityForResult.createIntent(ActivityResultContracts.kt:59)
    at androidx.activity.ComponentActivity$1.onLaunch(ComponentActivity.java:197)
    at androidx.activity.result.ActivityResultRegistry$3.launch(ActivityResultRegistry.java:244)
    at androidx.activity.result.ActivityResultLauncher.launch(ActivityResultLauncher.java:47)
    at androidx.fragment.app.FragmentManager.launchStartActivityForResult(FragmentManager.java:2880)
    at androidx.fragment.app.Fragment.startActivityForResult(Fragment.java:1505)
    at androidx.fragment.app.Fragment.startActivityForResult(Fragment.java:1474)
    at com.docusign.androidsdk.ui.fragments.OnlineSigningFragment$onFileChooser$1.onCameraAccessGranted(OnlineSigningFragment.kt:669)
    at com.docusign.androidsdk.ui.activities.DSIActivity.onRequestPermissionsResult(DSIActivity.kt:169)
    at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:9262)
    at android.app.Activity.dispatchActivityResult(Activity.java:9120)
    at android.app.ActivityThread.deliverResults(ActivityThread.java:5891)
```

**Environment Details:**

OS Version: Android 14 (API 34) (but based on Firebase crash logs it happens on other versions too)
SDK Version: 1.9.5

**Comment by naveentds** [comment] 2024-08-13 15:24
Hi
We will look into this issue and fix will be available in next release v1.9.6
Thanks.

**Comment by oguzozcan** [comment] 2024-08-15 09:23
Hello, do you have an estimation for the next release? Approximately when it will happen?

**Comment by naveentds** [comment] 2024-08-15 17:10
Hi
We are planning our next SDK release in the first week of September.

**Comment by naveentds** [comment] 2024-09-03 20:13
Hi
We released SDK v1.9.6. Please try it out and let us know how it goes.

**Comment by vdrahorad-paylocity** [comment] 2024-09-04 08:40
Hello,

I have retested with version 1.9.6. The app no longer crashes when declining the permission, but it crashes when accepting the permission after disabling the camera (this is an edge case, as we don’t expect many users to disable the camera app).

Steps to reproduce:

1. Disable the Camera app in device settings.
2. Tap Upload Signature.
3. Grant the Camera permission when prompted.

error log:
```
java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=2, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.paylocity.ngmobileqa.debug/com.docusign.androidsdk.ui.activities.CaptiveSigningActivity}: java.lang.NullPointerException: Parameter specified as non-null is null: method androidx.activity.result.contract.ActivityResultContracts$StartActivityForResult.createIntent, parameter input
    at android.app.ActivityThread.deliverResults(ActivityThread.java:5898)
    at android.app.ActivityThread.handleSendResult(ActivityThread.java:5937)
    at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
    at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:144)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:101)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2643)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:257)
    at android.os.Looper.loop(Looper.java:368)
    at android.app.ActivityThread.main(ActivityThread.java:8839)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method androidx.activity.result.contract.ActivityResultContracts$StartActivityForResult.createIntent, parameter input
    at androidx.activity.result.contract.ActivityResultContracts$StartActivityForResult.createIntent(Unknown Source:9)
    at androidx.activity.result.contract.ActivityResultContracts$StartActivityForResult.createIntent(ActivityResultContracts.kt:59)
    at androidx.activity.ComponentActivity$1.onLaunch(ComponentActivity.java:197)
    at androidx.activity.result.ActivityResultRegistry$3.launch(ActivityResultRegistry.java:244)
    at androidx.activity.result.ActivityResultLauncher.launch(ActivityResultLauncher.java:47)
    at androidx.fragment.app.FragmentManager.launchStartActivityForResult(FragmentManager.java:2880)
    at androidx.fragment.app.Fragment.startActivityForResult(Fragment.java:1505)
    at androidx.fragment.app.Fragment.startActivityForResult(Fragment.java:1474)
    at com.docusign.androidsdk.ui.fragments.OnlineSigningFragment$onFileChooser$1.onCameraAccessGranted(OnlineSigningFragment.kt:686)
    at com.docusign.androidsdk.ui.activities.DSIActivity.onRequestPermissionsResult(DSIActivity.kt:170)
    at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:9262)
    at android.app.Activity.dispatchActivityResult(Activity.java:9120)
    at android.app.ActivityThread.deliverResults(ActivityThread.java:5891)
    at android.app.ActivityThread.handleSendResult(ActivityThread.java:5937)
    at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
    at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:144)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:101)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2643)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:257)
    at android.os.Looper.loop(Looper.java:368)
    at android.app.ActivityThread.main(ActivityThread.java:8839)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
```

**Comment by naveentds** [comment] 2024-09-04 16:44
Hi,
As this is an edge case where users will disable camera app, we will look into fixing this issue in future releases. 
You can create a separate issue with this info. We can close the current issue as the original issue got resolved.

**Comment by naveentds** [comment] 2024-09-17 20:30
We hope the issue is resolved. Closing this issue for now.

**Closed as completed by naveentds** 2024-09-17 20:30 UTC
