### ISSUE TITLE
Can't resolve symbol 'init'

### ISSUE THREAD

**Issue by liuxihan** [docusign/mobile-android-sdk#10] opened 2020-11-05 06:47 UTC
Hi, 

After setting up the environment and including the library, the DocuSign.init() could not be resolved by Android Studio. How should I get this function?

**Comment by naveentds** [comment] 2020-11-05 17:43
Hi @liuxihan,
Please check if you have done the following setup in your project. 
  
## Setup 
1. In your application's root build.gradle file:
   ```gradle
   allprojects {
      repositories {
        google()
        jcenter()
 
        maven {
            url  "https://dl.bintray.com/dsdevcenter/maven"
        }
      }
    }
    ```
2. In your application's app-level build.gradle file:
    ```gradle
    android {
        defaultConfig {
            multiDexEnabled = true
        }
    }
    
    dependencies {
        implementation 'com.docusign:androidsdk:1.1.1'
    }
    
    ```

## Initialization
```java
DocuSign.init(
    this, // the Application Context
    "[YOUR INTEGRATION KEY HERE]", // recommend not hard-coding this
    DSMode.DEBUG // this controls the logging (logcat) behavior
);
```

### Initialization for OAuth Login
In your application's Application class:
```java
DocuSign.init(
     this, // the Application Context
     "[YOUR INTEGRATION KEY HERE]", // Same as Client Id
     "[YOUR CLIENT SECRET KEY]",
     "[YOUR REDIRECT_URI]",
     DSMode.Debug  
);
DocuSign.getInstance().setEnvironment(DSEnvironment.DEMO_ENVIRONMENT); // For Demo environment. For production environment, use DSEnvironment.PRODUCTION_ENVIRONMENT
```

If still does not get resolved, try InvalidateCaches/Restart in your Android Studio.

**Comment by liuxihan** [comment] 2020-11-10 09:29
Thanks for the reply.@naveentds  I solved it by myself. The issue was that DocuSign does not have the init() function which should be DocuSign.Companion.init(). I think it would be better for later developers to know this modification by changing the readme if it is possible. But, thank you!

**Comment by liuxihan** [comment] 2020-11-17 10:43
E/com.pdftron.pdf.PDFNet: PDFNet has already been initialized! `PDFNet.initialize(...)` should only be called 1 single time!
Hi, again! I used the initialize envelope `DSEnvelope envelope = new DSEnvelope.Builder()
                    .envelopeName("new envelope")
                    .document(new DSDocument.Builder()
                            .documentId(1)
                            .uri("file://Downloads")
                            .name("SignThis")
                            .build())` but it gave me PDFNet error. 
Thank you

**Comment by naveentds** [comment] 2020-11-17 16:04
Please find the code below for creating an envelope:

```java
   private DSEnvelope buildEnvelope(File document) {
        try {
            DSAuthenticationDelegate authenticationDelegate =
                    DocuSign.getInstance().getAuthenticationDelegate();
            DSUser user = authenticationDelegate.getLoggedInUser(getApplicationContext());
            URI fileURI = document.toURI();
            return new DSEnvelope.Builder()
                    .envelopeName("TestEnvelope")
                    .document(new DSDocument.Builder()
                            .documentId(1)
                            .uri(fileURI.toString())
                            .name("TestDocument")
                            .build())
                    .recipient(new DSEnvelopeRecipient.Builder()
                            .recipientId(1)
                            .routingOrder(1)
                            // this should be the user returned in DSAuthenticationListener.
                            .hostName(user.getName())
                            .hostEmail(user.getEmail())
                            .signerName("John")
                            .signerEmail("john@gmail.com")
                            .type(DSRecipientType.IN_PERSON_SIGNER)
                            .tab(new DSTab.Builder()
                                    .documentId(1)
                                    .recipientId(1)
                                    // the page on which this tab should appear
                                    .pageNumber(1)
                                    // the x-coordinate on page 1
                                    .xPosition(370)
                                    // the y-coordinate on page 1
                                    .yPosition(620)
                                    .type(DSTabType.SIGNATURE)
                                    .build())
                            .build())
                    .recipient(new DSEnvelopeRecipient.Builder()
                            .recipientId(2)
                            .routingOrder(2)
                            // this should be the user returned in DSAuthenticationListener.
                            .hostName(user.getName())
                            .hostEmail(user.getEmail())
                            .signerName("Pat")
                            .signerEmail("pat@gmail.com")
                            .type(DSRecipientType.IN_PERSON_SIGNER)
                            .tab(new DSTab.Builder()
                                    .documentId(1)
                                    .recipientId(2)
                                    // the page on which this tab should appear
                                    .pageNumber(1)
                                    // the x-coordinate on page 1 
                                    .xPosition(80)
                                    // the y-coordinate on page 1 
                                    .yPosition(620)
                                    .type(DSTabType.SIGNATURE)
                                    .build())
                            .build())
                    // this recipient receives a copy
                    .recipient(new DSEnvelopeRecipient.Builder()
                            .recipientId(3)
                            .routingOrder(3)
                            // if someone needs a signed copy, their name here
                            .signerName("Jack Doe")
                            .signerEmail("jack.doe@gmail.com")
                            .type(DSRecipientType.CARBON_COPY)
                            .build())
                    .textCustomFields(
                            // this is for free-form metadata
                            this.getTextCustomFields()
                    )
                    .build();
        } catch (DSEnvelopeException
                | DocuSignNotInitializedException | DSAuthenticationException exception) {
            if (exception.getMessage() != null) {
                Log.e(TAG, exception.getMessage());
            }
        }
        return null;
   }

   private List<DSTextCustomField> getTextCustomFields() {

        DSTextCustomField textCustomField1, textCustomField2;
        List<DSTextCustomField> textCustomFields = new ArrayList<>();
        try {
            textCustomField1 = new DSTextCustomField.Builder()
                    .fieldId(123)
                    .name("metadata1")
                    .value("some value")
                    .build();
            textCustomField2 = new DSTextCustomField.Builder()
                    .fieldId(234)
                    .name("metadata2")
                    .value("some value 2")
                    .build();
            textCustomFields.add(textCustomField1);
            textCustomFields.add(textCustomField2);
        } catch (DSEnvelopeException exception) {
            if (exception.getMessage() != null) {
                Log.e(TAG, exception.getMessage());
            }
        }

        return textCustomFields;
   }
```
Once envelope is created, you can send envelope as follows: 
```java
try {
    DSEnvelopeDelegate docusignEnvelopeDelegate = DocuSign.getInstance().getEnvelopeDelegate();
    docusignEnvelopeDelegate.composeAndSendEnvelope(envelope, new ComposeAndSendEnvelopeListener() {
        @Override
        public void onSuccess(@NonNull String envelopeId) {
            // At this point, the Envelope will be successfully created in local db store
            // TODO: this is where Signing will kickoff
        }
 
        @Override
        public void onError(@NonNull DSEnvelopeException exception) {
            // TODO: handle failed envelope creation. exception.getMessage() will indicate what went wrong
        }
    });
} catch (DocuSignNotInitializedException exception) {
    // TODO: handle error. This means the SDK object was not properly initialized
}
```

**Comment by liuxihan** [comment] 2020-11-19 10:34
Hi, @naveentds. Thanks for the reply! I used your codes, but it still gave me the exception error: file is not a valid, parseable, password-free PDF. The pdf I uploaded was the one I tested on the DocuSign website. I am wondering how this exception generated? Thanks again!

**Comment by naveentds** [comment] 2020-11-19 18:36
Hi @liuxihan, 
DocuSign SDK does not support password protected/encrypted PDF files.

**Comment by liuxihan** [comment] 2020-11-20 06:54
Hi @naveentds The file I used does not have any password and isn't protected/encrypted.

**Comment by skongara** [comment] 2020-11-20 18:57
Hi @liuxihan, DocuSign website accepts all types of file like jpg, doc etc, where as Android SDK accepts only pdf files (without password protected or encrypted). If you are using pdf file and still seeing this issue, if possible, can you please attach the pdf file you are using? We would like to test it with that pdf. Thanks!

**Comment by liuxihan** [comment] 2020-12-03 08:13
Hi, @skongara Sorry for the late reply. I would be so grateful if you could help me to test this file. Thank you so much!
[Sign.pdf](https://github.com/docusign/mobile-android-sdk/files/5634583/Sign.pdf)

**Comment by skongara** [comment] 2020-12-03 18:41
@liuxihan I tried offline signing with the attached envelope and it is working fine. I stored the file in the app's assets folder and passed its path to uri while creating the document via buildEnvelope() as mentioned in earlier conversation. The path looks like "file:/data/user/0/{applicationPackageName}/files/Sign.pdf.

Can you let us know how you are passing the document ?

**Comment by naveentds** [comment] 2021-02-12 02:21
Closing issue hoping the issue is resolved.

**Closed as completed by naveentds** 2021-02-12 02:21 UTC

**Comment by MAkif06** [comment] 2022-07-21 06:37
![Ekran Görüntüsü (32)](https://user-images.githubusercontent.com/96817707/180145810-dc559df4-c147-4943-b45c-edb2bfb2479e.png)

Hi, I trying to add YoutubePlayer to my android project. But I am getting this error.Do you have any idea?
