### ISSUE TITLE
Error throws from Docusign SDK 

### ISSUE THREAD

**Issue by meeramanesh** [docusign/mobile-android-sdk#29] opened 2022-03-08 15:17 UTC
After signing the DocuSign pdf ,  if app is allowed to run in background and relaunch again Docusign SDK throws the below error, with any updates in the callback 

java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
at androidx.fragment.app.FragmentManager.checkStateLoss(FragmentManager.java:1844)
at androidx.fragment.app.FragmentManager.enqueueAction(FragmentManager.java:1884)
at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:329)
at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:294)
at com.docusign.androidsdk.ui.activities.OnlineSigningActivity.signingFinished(OnlineSigningActivity.kt:643)
at com.docusign.androidsdk.ui.fragments.OnlineSigningFragment.didHandleUrlEvent(OnlineSigningFragment.kt:523)
at com.docusign.androidsdk.ui.fragments.OnlineSigningFragment.shouldOverrideUrlLoading(OnlineSigningFragment.kt:382)
at com.docusign.androidsdk.ui.activities.DSWebViewClient.shouldOverrideUrlLoading(DSWebActivity.kt:166)
at com.docusign.androidsdk.ui.activities.DSWebViewClient.shouldOverrideUrlLoading(DSWebActivity.kt:171)
at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(chromium-TrichromeWebViewGoogle6432.apk-stable-447211487:14)
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:335)
at android.os.Looper.loopOnce(Looper.java:161)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7839)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
E/DocuSign_DSMTelemetryDelegate: Can not perform this action after onSaveInstanceState

**Comment by naveentds** [comment] 2022-03-09 16:53
Hi @meeramanesh we will try to reproduce this issue and address this in our next release.

**Comment by naveentds** [comment] 2022-03-23 23:11
Hi @meeramanesh This issue is fixed in SDK v1.5.4 which was published today. Can you try with this SDK version and let us know if the issue is resolved.

**Comment by meeramanesh** [comment] 2022-03-24 13:51
We have upgraded the new version 1.5.4. Which works fine. The issue is resolved. Thanks a lot

**Closed as completed** 2022-03-25 20:07 UTC
