### ISSUE TITLE
Radiobutton displays as Checkbox

### ISSUE THREAD

**Issue by meeramanesh** [docusign/mobile-android-sdk#44] opened 2023-05-29 13:33 UTC
Hi Team Good Day,
I have configured my template with a Radio button group.
When I tried to do online signing from Android app,  the radio button shows as checkbox. Where as in iOS(offline signing) the radio button shows properly.
Kindly help me to resolve the issue.

Thanks,
Meera Manesh

**Comment by kamran-DS** [comment] 2023-05-29 17:13
Hi Meera, 

Thanks for your message. I believe you're referencing the DocuSIgn App within Google Play Store / Apple App Store. If so, please open a ticket at support.docusign.com and one of our support engineers will help you through this. 

Thanks, 
Kamran.

**Comment by naveentds** [comment] 2023-05-30 17:38
Hi Meera
In the ticket, please provide the template so that we will try to reproduce the issue on our end. 

Thanks
Naveen

**Comment by meeramanesh** [comment] 2023-06-01 04:07
Hi Naveen,
I couldn't provide the template due to some security reasons.
The scenario is as below

1. New template uploaded in docusign
2. Added radio buttons in the templates
3. While doing online signing from Android SDK, the radio button is displayed as checkbox.
4. iOS is doing offline signing, in this case its showing radio button properly.

**Comment by naveentds** [comment] 2023-06-01 16:19
Hi Meera
Can you provide the screenshot of the issue.

Thanks.

**Comment by meeramanesh** [comment] 2023-06-02 09:46
Hi Naveen,

Its better to schedule a call and discuss about this issue. Due to security concerns I couldn't share the screenshots

Thanks, 
Meera

**Comment by naveentds** [comment] 2023-06-02 15:43
Hi @kamran-DS 
Please set up a call with Meera to discuss about the issue.
Thanks.

**Comment by meeramanesh** [comment] 2023-06-05 07:12
Hi Naveen,

All the required information has been sent to your support team by raising a ticket.

Thanks in Advance.

**Comment by HunterWDocu** [comment] 2023-06-12 20:54
Hi @meeramanesh,

My name is Hunter and I'm a developer support engineer with DocuSign. You mentioned that you've created a ticket and sent over the information Naveen here requested. Do you by change had the case number? I want to make sure you case is properly handled by our developer support team and ensure it wasn't incorrectly routed to a different support team. If you rather not share the case number here you can always mention in the case thread that you'd like to work directly with developer support since we've been communicating via this Github issue.

Kindest regards,
Hunter - Developer Support

**Comment by HunterWDocu** [comment] 2023-06-12 21:16
Hi @meeramanesh,

My name is Hunter and I'm a developer support engineer with DocuSign. I took a look and saw that you have an open support ticket with our eSignature support team. It looks like they were able to schedule a call to discuss this issue with your team. Should this issue need more assistance we will be able to escalate through the case ticket for further steps.

Kindest regards,
Hunter - DocuSign Developer Support

**Comment by naveentds** [comment] 2023-07-03 22:13
Hi @meeramanesh @HunterWDocu , please let us know if the issue is resolved. If so, can you update the ticket accordingly.

**Comment by naveentds** [comment] 2023-07-24 18:11
Looks like the issue is resolved as per Dev support. Closing the issue.

**Closed as completed by naveentds** 2023-07-24 18:11 UTC
