### ISSUE TITLE
Usage of android support libraries

### ISSUE THREAD

**Issue by oguzozcan** [docusign/mobile-android-sdk#52] opened 2024-07-24 09:51 UTC
Hello,

When i am analysing my build's performance i can see that docusign android library is using legacy support libraries and its forcing us to enable jetifier for the whole project, which is increasing our build time.

Can this be resolved? Is there any chance that you could stop using legacy support libraries?
Thank you

**Comment by naveentds** [comment] 2024-07-24 17:09
Hi
We will look into this and will update in our future releases.
Thanks.

**Comment by naveentds** [comment] 2024-09-03 20:15
Hi
We released SDK v1.9.6. Please try it out and let us know how it goes.

**Comment by naveentds** [comment] 2024-09-17 20:23
We hope the issue is resolved. In case if there are any issues, please let us know. 
Closing this issue for now.

**Closed as completed by naveentds** 2024-09-17 20:23 UTC
